name: Check Unit Test

on: push

jobs:
  test:
    name: Testing TC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Menginstall Libcheck
        run: sudo apt install check
      - name: Membuat Folder
        run: mkdir bin build
      - name: Testing semua TC
        run: make test
